"""add profile fields to user

Revision ID: 8cee3ec088dd
Revises: 35fa8d09238d
Create Date: 2026-06-26 10:39:14.772361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cee3ec088dd'
down_revision = '35fa8d09238d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cycle_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('period_length', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('period_length')
        batch_op.drop_column('cycle_length')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
